############################################################
#
# web访问端口  约定：8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                  #数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      #数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver   #mysql驱动
    # url 如果是xml中写数据库连接，用转义符号&amp;代表分号，yml中写数据库配置连接用&即可
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1q1q1q1q
  hikari:
    connection-timeout: 30000                #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
    minimum-idle: 5                          #最小连接数
    maximum-pool-size: 20                    #最大连接数
    auto-commit: true                        #自动提交
    idle-timeout: 600000                     #连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
    pool-name: DateSourceHikariCP            #连接池名字
    max-lifetime: 1800000                    #连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
    connection-test-query: SELECT1
############################################################
#
# mybatis配置
#
############################################################
  mybatis:
    type-aliases-package: com.me.pojo     #所有POJO类所在包路径
    mapper-locations: classpath:mapper/*.xml #mapper映射文件

  ############################################################
  #
  # mybatismapper配置
  #
  ############################################################
  # 通用Mapper配置
  mapper:
    mappers: com.me.my.mapper.MyMapper
    not-empty: false  # 在进行数据库操作的时候，判断表达式 username != null, 是否追加 username != ''
    dentity: MYSQL # 数据库方言